# Generated by Django 5.2.3 on 2025-07-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_categoria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
