# Generated by Django 5.2.3 on 2025-07-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_alter_categoria_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
