# Generated by Django 5.2.3 on 2025-08-12 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.categoria'),
        ),
    ]
